/**
* This file is part of dev.clipall.
*
* dev.clipall is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* You should have received a copy of the GNU General Public License
* along with dev.clipall.  If not, see <http://www.gnu.org/licenses/>.
*
* File      : SearchFrame.java
* Created   : Oct 31, 2009, 5:16:38 PM
*/

package dev.clipall.view;

/**
 *
 * @author Erol Hira
 */
public class SearchFrame extends javax.swing.JFrame {

    private static SearchFrame searchFrame = new SearchFrame();

    private SearchFrame(){
        initComponents();
    }

    public static SearchFrame getInstance(){
        return searchFrame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = SearchPanel.getInstance();

        setTitle("ClipAll");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dev.clipall.view.SearchPanel searchPanel;
    // End of variables declaration//GEN-END:variables

    
    public void displaySearchFrame(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchFrame.getInstance().setVisible(true);
            }
        });
    }

    public void hideSearchFrame(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchFrame.getInstance().setVisible(false);
                //SearchFrame.getInstance().setState(ICONIFIED);
                //SearchFrame.getInstance().toBack();
                //SearchFrame.getInstance().dispose();
            }
        });
    }
}
